USE [Production]
GO

/****** Object:  Table [dbo].[resource_data]    Script Date: 7/3/2024 8:02:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[resource_data](
	[reservers_s] [int] IDENTITY(1,1) NOT NULL,
	[reported_date] [date] NULL,
	[fluid_name] [nvarchar](255) NULL,
	[business_associate_id] [nvarchar](255) NULL,
	[asset_id] [nvarchar](255) NULL,
	[block_name] [nvarchar](255) NULL,
	[block_id] [nvarchar](255) NULL,
	[pi_block_percentage] [float] NULL,
	[field_name] [nvarchar](255) NULL,
	[field_id] [nvarchar](255) NULL,
	[field_category] [nvarchar](255) NULL,
	[pi_field_percentage] [float] NULL,
	[iip_low_mstb] [float] NULL,
	[iip_best_mstb] [float] NULL,
	[iip_high_mstb] [float] NULL,
	[rf_to_iip_low_percentage] [float] NULL,
	[rf_to_iip_best_percentage] [float] NULL,
	[rf_to_iip_high_percentage] [float] NULL,
	[eur_low_mstb] [float] NULL,
	[eur_best_mstb] [float] NULL,
	[eur_high_mstb] [float] NULL,
	[prod_last_year_mstb] [float] NULL,
	[net_sales_last_year_mstb] [float] NULL,
	[own_use_last_year_mstb] [float] NULL,
	[injection_last_year_mstb] [float] NULL,
	[flare_last_year_mstb] [float] NULL,
	[impurities_last_year_mstb] [float] NULL,
	[shrinkage_last_year_mstb] [float] NULL,
	[cumulative_production_mstb] [float] NULL,
	[reserves_sales_curr_year_1pd_mstb] [float] NULL,
	[reserves_sales_curr_year_1pu_mstb] [float] NULL,
	[reserves_sales_curr_year_1p_mstb] [float] NULL,
	[reserves_sales_curr_year_2pd_mstb] [float] NULL,
	[reserves_sales_curr_year_2pu_mstb] [float] NULL,
	[reserves_sales_curr_year_2p_mstb] [float] NULL,
	[reserves_sales_curr_year_3pd_mstb] [float] NULL,
	[reserves_sales_curr_year_3pu_mstb] [float] NULL,
	[reserves_sales_curr_year_3p_mstb] [float] NULL,
	[fuel_curr_year_1pd_mstb] [float] NULL,
	[fuel_curr_year_1pu_mstb] [float] NULL,
	[fuel_curr_year_1p_mstb] [float] NULL,
	[fuel_curr_year_2pd_mstb] [float] NULL,
	[fuel_curr_year_2pu_mstb] [float] NULL,
	[fuel_curr_year_2p_mstb] [float] NULL,
	[fuel_curr_year_3pd_mstb] [float] NULL,
	[fuel_curr_year_3pu_mstb] [float] NULL,
	[fuel_curr_year_3p_mstb] [float] NULL,
	[total_reserves_curr_year_1pd_mstb] [float] NULL,
	[total_reserves_curr_year_1pu_mstb] [float] NULL,
	[total_reserves_curr_year_1p_mstb] [float] NULL,
	[total_reserves_curr_year_2pd_mstb] [float] NULL,
	[total_reserves_curr_year_2pu_mstb] [float] NULL,
	[total_reserves_curr_year_2p_mstb] [float] NULL,
	[total_reserves_curr_year_3pd_mstb] [float] NULL,
	[total_reserves_curr_year_3pu_mstb] [float] NULL,
	[total_reserves_curr_year_3p_mstb] [float] NULL,
	[reserves_sales_last_year_1pd_mstb] [float] NULL,
	[reserves_sales_last_year_1pu_mstb] [float] NULL,
	[reserves_sales_last_year_1p_mstb] [float] NULL,
	[reserves_sales_last_year_2pd_mstb] [float] NULL,
	[reserves_sales_last_year_2pu_mstb] [float] NULL,
	[reserves_sales_last_year_2p_mstb] [float] NULL,
	[reserves_sales_last_year_3pd_mstb] [float] NULL,
	[reserves_sales_last_year_3pu_mstb] [float] NULL,
	[reserves_sales_last_year_3p_mstb] [float] NULL,
	[wdr_percentage] [float] NULL,
	[rtp_years] [float] NULL,
	[rrr_percentage] [float] NULL,
	[rf_to_eur_percentage] [float] NULL,
	[rrr_from_add_p1_percentage] [float] NULL,
	[rf_to_in_place_percentage] [float] NULL,
	[add_reserve_last_year_recoverable_1p_mstb] [float] NULL,
	[add_reserve_last_year_recoverable_2p_mstb] [float] NULL,
	[add_reserve_last_year_recoverable_3p_mstb] [float] NULL,
	[add_contingent_last_year_recoverable_1c_mstb] [float] NULL,
	[add_contingent_last_year_recoverable_2c_mstb] [float] NULL,
	[add_contingent_last_year_recoverable_3c_mstb] [float] NULL,
	[contingent_curr_year_recoverable_1c_mstb] [float] NULL,
	[contingent_curr_year_recoverable_2c_mstb] [float] NULL,
	[contingent_curr_year_recoverable_3c_mstb] [float] NULL,
	[contingent_last_year_recoverable_1c_mstb] [float] NULL,
	[contingent_last_year_recoverable_2c_mstb] [float] NULL,
	[contingent_last_year_recoverable_3c_mstb] [float] NULL,
	[remarks] [nvarchar](255) NULL,
	[sub_classification] [nvarchar](255) NULL,
	[delta_reserves_1p_mstb] [float] NULL,
	[delta_reserves_2p_mstb] [float] NULL,
	[delta_reserves_3p_mstb] [float] NULL,
	[delta_contingent_1c_mstb] [float] NULL,
	[delta_contingent_2c_mstb] [float] NULL,
	[delta_contingent_3c_mstb] [float] NULL,
	[structure_name] [nvarchar](255) NULL,
	[nsf_1p] [float] NULL,
	[nsf_2p] [float] NULL,
	[nsf_3p] [float] NULL,
	[nsf_1c] [float] NULL,
	[nsf_2c] [float] NULL,
	[nsf_3c] [float] NULL,
	[row_created_by] [nvarchar](255) NULL,
	[row_created_date] [nvarchar](255) NULL,
	[active_ind] [nvarchar](255) NULL,
	[row_effective_date] [nvarchar](255) NULL,
	[row_expiry_date] [nvarchar](255) NULL,
	[row_quality] [nvarchar](255) NULL,
	[area_id] [varchar](255) NULL,
 CONSTRAINT [PK__tes1}__C5F9760ECC6865EC] PRIMARY KEY CLUSTERED 
(
	[reservers_s] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


